### ISSUE TITLE
BUG - mockserver has dependencies to ui5-tooling v2

### ISSUE THREAD

**Issue by BenReim** [SAP/open-ux-odata#798]
### Description
The current mockserver release still declares a dependency to `@ui5/logger@2.x` thus npm warning logs are raised such as:
`.npm WARN deprecated @ui5/logger@2.0.1: UI5 Tooling version 2 is out of maintenance. Migrate your project to the latest version: https://sap.github.io/ui5-tooling/stable/`

### Steps to reproduce
```shell
 $ npm ls @ui5/logger
  ├─┬ @sap-ux/ui5-middleware-fe-mockserver@2.2.31
  │ └─┬ @sap-ux/fe-mockserver-core@1.2.31
  │   └── @ui5/logger@2.0.1
[...]
```

**Comment by GuillaumedesPommareSAP** [comment]
When fixing this issue, would it be possible to think about an indirection to the logging tooling ?
We embed ui5-middleware-fe-mockserver in our own express test server, and there is no entry point (to my knowledge) to plug our own logging library, here winston, so that we can route logs into our logging system.

As this is a modular approach, setting a logger would be a very nice addition!

**Comment by nlunets** [comment]
Sorry for the delay, fixed with [@sap-ux/ui5-middleware-fe-mockserver@2.2.78]
And @GuillaumedesPommareSAP you can also specify a logger now :)
